version: '3.8'

networks:
  wallet-net:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  logstash_pipeline:
  redis_data:

services:
  # 🛢️ PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: wallet-postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_pass
      - POSTGRES_DB=wallet
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - wallet-net

  # 📦 Zookeeper (Required for Kafka)
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: wallet-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - wallet-net

  # 📨 Kafka (Message Broker)
  kafka:
    image: bitnami/kafka:latest
    container_name: wallet-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - wallet-net

  # 🔍 Elasticsearch (Search Engine)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: wallet-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - wallet-net

  # 📊 Kibana (Visualization)
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: wallet-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://wallet-elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - wallet-net

  # 📑 Logstash (Data Processing Pipeline) - Integrado com PostgreSQL, Keycloak, Kafka, Redis
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.7
    container_name: wallet-logstash
    depends_on:
      - elasticsearch
      - redis
      - kafka
      - postgres
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    environment:
      - XPACK_MONITORING_ENABLED=false
    networks:
      - wallet-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5044"]
      interval: 10s
      timeout: 5s
      retries: 5  
      

  # 📈 Prometheus (Monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: wallet-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - wallet-net

  # 🚀 Redis (Cache & Message Broker)
  redis:
    image: redis:7
    container_name: wallet-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wallet-net
    command: redis-server --save 60 1 --loglevel warning

  #   # 🚀 Wallet Service (Spring Boot + WebFlux)
  wallet-service:
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    container_name: wallet-service
    ports:
      - "8073:8073"
    environment:
      - PORT=8073
      - DATABASE_URL=wallet-postgres:5432
      - DATABASE_NAME=wallet
      - DATABASE_USER=wallet_user
      - DATABASE_PASSWORD=wallet_pass
      - REDIS_URL=wallet-redis
      - REDIS_PORT=6379
      - KAFKA_URL_AND_PORT=wallet-kafka:9092
      - PROMETHEUS_URL=http://wallet-prometheus:9090
      - LEVEL_LOGGING=INFO
      - KAFKA_LEVEL_LOGGING=WARN
      - MICROMETER_LEVEL_LOGGING=WARN
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      - postgres
      - redis
      - kafka
      - prometheus
      - logstash
    networks:
      - wallet-net  
