global:
  scrape_interval: 15s  # Intervalo padrão de coleta de métricas (a cada 15 segundos)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wallet-service'
    metrics_path: '/actuator/prometheus'  # Padrão do Spring Boot Micrometer
    static_configs:
      - targets: ['wallet-service:8080']  # Nome do container do seu serviço

  - job_name: 'kafka'
    static_configs:
      - targets: ['wallet-kafka:9308']  # Porta padrão do Exporter do Kafka

  - job_name: 'postgres'
    static_configs:
      - targets: ['wallet-postgres:9187']  # Porta do Postgres Exporter (se configurado)

  - job_name: 'logstash'
    static_configs:
      - targets: ['wallet-logstash:9600']  # Porta de monitoramento do Logstash
